import {
	ejectAllDisks,
	emptyTrash,
	getFrontmostApp,
	getSelectedFilesInFileExplorer,
	hideAllAppsExceptFrontmost,
	logoutUser,
	mute,
	openTrash,
	quitAllApps,
	reboot,
	setVolume,
	setVolumeTo0,
	setVolumeTo25,
	setVolumeTo50,
	setVolumeTo75,
	setVolumeTo100,
	showDesktop,
	shutdown,
	sleep,
	sleepDisplays,
	toggleBluetooth,
	toggleHiddenFiles,
	toggleMute,
	toggleStageManager,
	toggleSystemAppearance,
	turnVolumeDown,
	turnVolumeUp,
	unmute
} from "../../commands/system"
import { type ISystem } from "../client"

// const defaultClientAPI = getDefaultClientAPI<ISystemServer>()

// export const comlinkSystem: ISystem = {
// 	openTrash: defaultClientAPI.systemOpenTrash,
// 	emptyTrash: defaultClientAPI.systemEmptyTrash,
// 	shutdown: defaultClientAPI.systemShutdown,
// 	reboot: defaultClientAPI.systemReboot,
// 	sleep: defaultClientAPI.systemSleep,
// 	toggleSystemAppearance: defaultClientAPI.systemToggleSystemAppearance,
// 	showDesktop: defaultClientAPI.systemShowDesktop,
// 	quitAllApps: defaultClientAPI.systemQuitAllApps,
// 	sleepDisplays: defaultClientAPI.systemSleepDisplays,
// 	setVolume: defaultClientAPI.systemSetVolume,
// 	setVolumeTo0: defaultClientAPI.systemSetVolumeTo0,
// 	setVolumeTo25: defaultClientAPI.systemSetVolumeTo25,
// 	setVolumeTo50: defaultClientAPI.systemSetVolumeTo50,
// 	setVolumeTo75: defaultClientAPI.systemSetVolumeTo75,
// 	setVolumeTo100: defaultClientAPI.systemSetVolumeTo100,
// 	turnVolumeUp: defaultClientAPI.systemTurnVolumeUp,
// 	turnVolumeDown: defaultClientAPI.systemTurnVolumeDown,
// 	toggleStageManager: defaultClientAPI.systemToggleStageManager,
// 	toggleBluetooth: defaultClientAPI.systemToggleBluetooth,
// 	toggleHiddenFiles: defaultClientAPI.systemToggleHiddenFiles,
// 	ejectAllDisks: defaultClientAPI.systemEjectAllDisks,
// 	logoutUser: defaultClientAPI.systemLogoutUser,
// 	toggleMute: defaultClientAPI.systemToggleMute,
// 	mute: defaultClientAPI.systemMute,
// 	unmute: defaultClientAPI.systemUnmute,
// 	getFrontmostApp: defaultClientAPI.systemGetFrontmostApp,
// 	hideAllAppsExceptFrontmost: defaultClientAPI.systemHideAllAppsExceptFrontmost,
// 	getSelectedFilesInFileExplorer: defaultClientAPI.systemGetSelectedFilesInFileExplorer
// }

export const nativeSystem: ISystem = {
	ejectAllDisks,
	emptyTrash,
	getFrontmostApp,
	getSelectedFilesInFileExplorer,
	hideAllAppsExceptFrontmost,
	logoutUser,
	mute,
	openTrash,
	quitAllApps,
	reboot,
	setVolume,
	setVolumeTo0,
	setVolumeTo25,
	setVolumeTo50,
	setVolumeTo75,
	setVolumeTo100,
	showDesktop,
	shutdown,
	sleep,
	sleepDisplays,
	toggleBluetooth,
	toggleHiddenFiles,
	toggleMute,
	toggleStageManager,
	toggleSystemAppearance,
	turnVolumeDown,
	turnVolumeUp,
	unmute
}

// export const system = isMain() ? nativeSystem : comlinkSystem
