[package]
name = "mac-security-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
core-foundation = "0.10.0"
localauthentication-rs = "0.1.0"
objc = "0.2.7"
serde = { workspace = true, features = ["derive"] }
