name: Publish
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        working-directory: ./packages/api
        run: npx jsr publish --allow-slow-types
